# Generated by Django 6.0 on 2025-12-27 02:43

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productoboliviano',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='productoboliviano',
            name='stock',
        ),
        migrations.AlterField(
            model_name='productoboliviano',
            name='imagen',
            field=cloudinary.models.CloudinaryField(default='default', max_length=255, verbose_name='imagen'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productoboliviano',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
